"""PDF rendering for medical-tourism cost estimates."""

import os
import tempfile

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def generate_pdf_report(patient_details: dict, cost_predictions: dict) -> str:
    pdf_path = os.path.join(tempfile.gettempdir(), "medical_budget_report.pdf")
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 20)
    c.drawString(180, height - 50, "Medical Tourism Budget Report")

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 100, "Patient Details:")
    c.setFont("Helvetica", 12)
    y = height - 120
    for key, value in patient_details.items():
        c.drawString(70, y, f"{key}: {value}")
        y -= 20

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 20, "Estimated Costs:")
    c.setFont("Helvetica", 12)
    y -= 40
    for key, value in cost_predictions.items():
        c.drawString(70, y, f"{key}: {value}")
        y -= 20

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Disclaimer: These are estimated costs generated by AI. Actual costs may vary.")
    c.save()
    return pdf_path
